### ISSUE TITLE
#TODO

### ISSUE THREAD

**Issue by GHeeJeon** [my-ggott-games/oort-cloud#1]
- [x] 이미지 선정
- [x] 데이터 추출 (채팅 목록, txt 파일)
- [x] 구현 - 데이터 불러오기
- [x] 구현 - 데이터 추출하기(string)
- [x] 구현 - 의미없는 키워드 배제 1 (날짜, 시간 등 - 슬라이싱으로 활용할 것)
- [x] 구현 - 워드클라우드 생성
- [x] 구현 - 의미없는 키워드 배제 2 (ㅋㅋㅋ, ㅇㅇ 등 - 하나하나 배제할 것)
- [x] 구현 - 이미지에 맞는 워드클라우드 생성
- [x] 생성된 워드클라우드 고화질 이미지 저장
- [x] 워드클라우드 꾸미기(색상, 폰트)

~구현 - 형태소 분석~
~이미지 가공(흑백화)~

**Comment by GHeeJeon** [comment]
> 구현 - 형태소 분석

형태소 분석이 원하는대로 안 나온다. 커스텀 형태소 분석기를 하나 만들어야 하나...

**Comment by GHeeJeon** [comment]
> 구현 - 의미없는 키워드 배제 1 (날짜, 시간 등 - 슬라이싱으로 활용할 것)

[정규식](https://regex101.com/)으로 해결!

**Comment by GHeeJeon** [comment]
> 워드클라우드 꾸미기(색상, 폰트

와 [이거](https://github.com/amueller/word_cloud)다
